//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weapsy.Resources.Areas.Admin {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal App() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weapsy.App", typeof(App).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New App.
        /// </summary>
        public static string Button_NewApp {
            get {
                return ResourceManager.GetString("Button_NewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Add New App.
        /// </summary>
        public static string Button_NewApp_Title {
            get {
                return ResourceManager.GetString("Button_NewApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Are you sure you want to delete this app?.
        /// </summary>
        public static string ConfirmDelete_Message {
            get {
                return ResourceManager.GetString("ConfirmDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete_Title {
            get {
                return ResourceManager.GetString("ConfirmDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description Help....
        /// </summary>
        public static string Field_Description_Help {
            get {
                return ResourceManager.GetString("Field_Description_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Folder.
        /// </summary>
        public static string Field_Folder {
            get {
                return ResourceManager.GetString("Field_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Folder Help....
        /// </summary>
        public static string Field_Folder_Help {
            get {
                return ResourceManager.GetString("Field_Folder_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name Help....
        /// </summary>
        public static string Field_Name_Help {
            get {
                return ResourceManager.GetString("Field_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        public static string Grid_Description {
            get {
                return ResourceManager.GetString("Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Grid_Name {
            get {
                return ResourceManager.GetString("Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Saving App....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create New App.
        /// </summary>
        public static string Title_Create {
            get {
                return ResourceManager.GetString("Title_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit App.
        /// </summary>
        public static string Title_Edit {
            get {
                return ResourceManager.GetString("Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Apps.
        /// </summary>
        public static string Title_Index {
            get {
                return ResourceManager.GetString("Title_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enter the App Name.
        /// </summary>
        public static string Validation_NameRequired {
            get {
                return ResourceManager.GetString("Validation_NameRequired", resourceCulture);
            }
        }
    }
}
